services:
  db:
    container_name: postgresDB
    image: postgres
    environment:
      POSTGRES_USER: canok
      POSTGRES_PASSWORD: pass-123
      #POSTGRES_DB: empmngmnt

    ports:
      - "5432:5432"
